<a href="https://colab.research.google.com/github/BartoszJanJerzy/M-L-Bootcamp-cz.1/blob/master/04_train_test_split.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import pandas as pd
import sklearn
import seaborn as sns

np.random.seed(42)
np.set_printoptions(edgeitems=30, linewidth=100000, formatter=dict(float=lambda x: f'{x:.2f}'))

sns.set()

/usr/local/lib/python3.6/dist-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm


##Załadowanie danych

In [4]:
from sklearn.datasets import load_iris

raw_data = load_iris()
raw_data_copy = raw_data.copy()
raw_data_copy.keys()

dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names', 'filename'])

#Przygotowanie danych

In [5]:
data = raw_data_copy['data']
target = raw_data_copy['target']

print(f'{data[:5]}\n')
print(target[:5])

[[5.10 3.50 1.40 0.20]
 [4.90 3.00 1.40 0.20]
 [4.70 3.20 1.30 0.20]
 [4.60 3.10 1.50 0.20]
 [5.00 3.60 1.40 0.20]]

[0 0 0 0 0]


In [6]:
# połączenie predyktorów/atrybutów ze zmienną zależną/docelową
all_data = np.c_[data,target]
all_data[:5]

array([[5.10, 3.50, 1.40, 0.20, 0.00],
       [4.90, 3.00, 1.40, 0.20, 0.00],
       [4.70, 3.20, 1.30, 0.20, 0.00],
       [4.60, 3.10, 1.50, 0.20, 0.00],
       [5.00, 3.60, 1.40, 0.20, 0.00]])

In [7]:
#  budowa data frame
df = pd.DataFrame(data=all_data, columns=raw_data.feature_names + ['target'])
df.head()

sepal length (cm)  sepal width (cm)  ...  petal width (cm)  target
0                5.1               3.5  ...               0.2     0.0
1                4.9               3.0  ...               0.2     0.0
2                4.7               3.2  ...               0.2     0.0
3                4.6               3.1  ...               0.2     0.0
4                5.0               3.6  ...               0.2     0.0

[5 rows x 5 columns]

In [8]:
# statystyki opisowe + zaokrąglenie danych
df.describe().T.apply(lambda x: round(x, 2))

count  mean   std  min  25%   50%  75%  max
sepal length (cm)  150.0  5.84  0.83  4.3  5.1  5.80  6.4  7.9
sepal width (cm)   150.0  3.06  0.44  2.0  2.8  3.00  3.3  4.4
petal length (cm)  150.0  3.76  1.77  1.0  1.6  4.35  5.1  6.9
petal width (cm)   150.0  1.20  0.76  0.1  0.3  1.30  1.8  2.5
target             150.0  1.00  0.82  0.0  0.0  1.00  2.0  2.0

In [18]:
# rozkąłd zmiennej target
df.target.value_counts() #fajny sposó na histogram -> reset_index
temp

2.0    50
1.0    50
0.0    50
Name: target, dtype: int64

In [19]:
# podział DataFrame na data i target
data = df.copy()
target = data.pop('target')
data.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [20]:
target.head()

0    0.0
1    0.0
2    0.0
3    0.0
4    0.0
Name: target, dtype: float64

##Podział na zbiory treningowe i testowe

In [23]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(data, target, random_state=42)
'''
Inne parametry do funkcji train_test_split:
  test_size = ... procent zbioru testowego, np. 0.3; treningowy oblicza automatycznie
  train_size = ... procent zbioru treningowego, np. 0.9; testowy oblicza automatycznie
  stratify=target - równy podział zmiennej docelowej; przydaje się, gdy wystepuje dysproporcja w ilości kategorii w target, np. dużo kategorii 0, mało kategorii 1
'''


print(f'X_train shape {X_train.shape}')
print(f'X_test shape {X_test.shape}')
print(f'y_test shape {y_test.shape}')
print(f'y_train shape {y_train.shape}')
print(f'\nTest ratio: {len(X_test) / len(data):.2f}')
print(f'\ny_train: {y_train.value_counts()}')
print(f'\ny_test: {y_test.value_counts()}')

X_train shape (112, 4)
X_test shape (38, 4)
y_test shape (38,)
y_train shape (112,)

Test ratio: 0.25

y_train: 1.0    39
2.0    38
0.0    35
Name: target, dtype: int64

y_test: 0.0    15
2.0    12
1.0    11
Name: target, dtype: int64
