<a href="https://colab.research.google.com/github/BartoszJanJerzy/M-L-Bootcamp-cz.1/blob/master/05_regresja_rownanie_normalne.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

##Tworzenie danych

In [20]:
X1 = np.array([1,2,3,4,5,6])
Y = np.array([3000,3250,3500,3750,4000,4250])
m = len(X1)

print(f"Lata pracy {X1}")
print(f'Wynagrodzenie {Y}')
print(f'Liczba próbek {m}')

Lata pracy [1 2 3 4 5 6]
Wynagrodzenie [3000 3250 3500 3750 4000 4250]
Liczba próbek 6


In [26]:
# zmiana z listy na macierz
X1 = X1.reshape(m,1)
print(X1)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [16]:
# wektor wyrazów wolnych
bias = np.ones((m,1))
print(bias)

[[1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]]


In [17]:
# połączenie danych w lewą strone równania
X = np.append(bias, X1, axis=1)
print(X)

[[1. 1.]
 [1. 2.]
 [1. 3.]
 [1. 4.]
 [1. 5.]
 [1. 6.]]


Regresja liniowa w $R^2$:
$$Y = w_0 + w_1X_1$$
$$Y = W^TX$$
gdzie: $$W= \left[\begin{matrix}w_0\\w_1\end{matrix}\right]$$ $$ X= \left[\begin{matrix}1\\X_1\end{matrix}\right] $$ stąd $$ W^T= \left[\begin{matrix}w_0&w_1\end{matrix}\right] $$    
$$Y = W^TX = \left[\begin{matrix}w_0&w_1\end{matrix}\right] \cdot  \left[\begin{matrix}1\\X_1\end{matrix}\right] = w_0 + w_1X_1$$

Równanie normalne - równanie pozwalające obliczyć minimum funkcji straty (o ile istnieje)
$$W = (X^TX)^{-1}(X^TY)$$

In [18]:
# mnożenie macierzy (Xt * X)-1
L = np.linalg.inv(np.dot(X.T, X))
L

array([[ 0.86666667, -0.2       ],
       [-0.2       ,  0.05714286]])

In [21]:
# mnożenie macierzy Xt*Y
P = np.dot(X.T,Y)
P

array([21750., 80500.])

In [22]:
# mnożenei powstałych maceirzy przez siebie
W = np.dot(L,P)
W

array([2750.,  250.])

In [24]:
print(f"Y = {W[1]}*X + {W[0]}")

Y = 250.0*X + 2750.0


## A teraz za pomocą scikit-learn

In [29]:
from sklearn.linear_model import LinearRegression

X1 = np.array([1,2,3,4,5,6])
Y = np.array([3000,3250,3500,3750,4000,4250])
m = len(X1)

X1 = X1.reshape(m,1)

regression = LinearRegression()
regression.fit(X1,Y)

print(regression.intercept_)
print(regression.coef_)

2750.0
[250.]
